#ifndef INFLATE_INTERNAL_H
#define INFLATE_INTERNAL_H



#define INFLATE_MAX_CODE_LENGTH 15U
#define INFLATE_GENERAL_FAILURE (unsigned int)-1

/* Deflate defined constants (RFC 1951). */
#define INFLATE_END_OF_BLOCK_LITERAL    256U
#define INFLATE_LITERAL_CODE_COUNT      288UL
#define INFLATE_HIGHEST_LITERAL_CODE    285UL
#define INFLATE_DISTANCE_CODE_COUNT     32UL
#define INFLATE_HIGHEST_DISTANCE_CODE   29UL
#define INFLATE_CODE_LENGTH_CODE_COUNT  19UL



#endif /* INFLATE_INTERNAL_H */
